export type Photo = {
  src: string;
  alt: string;
  span: "tall" | "wide" | "square";
};

// Real photography by Isnad Bin Omar. Files live in /public/photography.
export const photos: Photo[] = [
  { src: "/photography/photo-001.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-002.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-003.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-004.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-005.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-006.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-007.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-008.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-009.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-010.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-011.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-012.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-013.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-014.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-015.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-016.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-017.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-018.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-019.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-020.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-021.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-022.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-023.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-024.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-025.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-026.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-027.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-028.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-029.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-030.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-031.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-032.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-033.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-034.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-035.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-036.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-037.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-038.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-039.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-040.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-041.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-042.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-043.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-044.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-045.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-046.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-047.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-048.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-049.jpg", alt: "Photography", span: "square" },
  { src: "/photography/photo-050.jpg", alt: "Photography", span: "wide" },
  { src: "/photography/photo-051.jpg", alt: "Photography", span: "tall" },
  { src: "/photography/photo-052.jpg", alt: "Photography", span: "wide" },
];
